const products = [
  {
    id: 1,
    slug: "samsung-galaxy-m17-5g",
    image: "https://m.media-amazon.com/images/I/41QOX6YsT5L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Samsung Galaxy M17 5G",
    company: "Samsung",
    price: 18999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Exynos 1380",
    display: "6.7-inch FHD+ Super AMOLED, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 8 MP + 2 MP",
    frontCamera: "13 MP",
    os: "Android 15 (One UI)",
    color: "Blue",
  },
  {
    id: 2,
    slug: "realme-c71-4g",
    image: "https://m.media-amazon.com/images/I/61yZ+3pjkYL._SX679_.jpg",
    brand: "realme C71 4G",
    company: "Realme",
    price: 15980,
    ram: "6 GB",
    storage: "128 GB",
    processor: "Unisoc T7250",
    display: "6.72-inch HD+ LCD, 120Hz",
    battery: "6300 mAh",
    camera: "50 MP AI Camera",
    frontCamera: "8 MP",
    os: "Android 15 (realme UI)",
    color: "Green",
  },
  {
    id: 3,
    slug: "motorola-edge-60-fusion",
    image: "https://m.media-amazon.com/images/I/61NsPikkMBL._SX679_.jpg",
    brand: "Motorola Edge 60 Fusion",
    company: "Motorola",
    price: 23999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 7400",
    display: "6.67-inch pOLED, 144Hz",
    battery: "5500 mAh",
    camera: "50 MP + 13 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "Forest Blue",
  },
  {
    id: 4,
    slug: "oppo-k14x-5g",
    image: "https://m.media-amazon.com/images/I/61wEl1TXntL._SX522_.jpg",
    brand: "OPPO K14x 5G",
    company: "OPPO",
    price: 15980,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 6300",
    display: "6.67-inch HD+ LCD, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "8 MP",
    os: "Android 15 (ColorOS)",
    color: "Midnight Violet",
  },
  {
    id: 5,
    slug: "acerpure-acerone-liquid-4g",
    image: "https://m.media-amazon.com/images/I/411RhleBYqL.jpg",
    brand: "Acerpure Acerone Liquid 4G",
    company: "Acer",
    price: 13599,
    ram: "6 GB",
    storage: "128 GB",
    processor: "MediaTek Helio G99",
    display: "6.78-inch FHD+ IPS LCD",
    battery: "5000 mAh",
    camera: "64 MP + 2 MP",
    frontCamera: "16 MP",
    os: "Android 14",
    color: "Black",
  },
  {
    id: 6,
    slug: "ikall-z10",
    image: "https://m.media-amazon.com/images/I/51UOnCphehL._SX679_.jpg",
    brand: "IKALL Z10",
    company: "IKALL",
    price: 11999,
    ram: "6 GB",
    storage: "128 GB",
    processor: "MediaTek Helio G85",
    display: "6.6-inch HD+ IPS LCD",
    battery: "5000 mAh",
    camera: "50 MP + AI Lens",
    frontCamera: "8 MP",
    os: "Android 14",
    color: "Black",
  },
  {
    id: 7,
    slug: "motorola-edge-60-pro",
    image: "https://m.media-amazon.com/images/I/71hbZwIVwQL._SY741_.jpg",
    brand: "Motorola Edge 60 Pro",
    company: "Motorola",
    price: 29999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 8350",
    display: "6.7-inch pOLED, 144Hz",
    battery: "6000 mAh",
    camera: "50 MP + 50 MP + 10 MP",
    frontCamera: "50 MP",
    os: "Android 15",
    color: "Pantone Shadow",
  },
  {
    id: 8,
    slug: "lava-agni-3",
    image: "https://m.media-amazon.com/images/I/71UdkYWXjCL._SX679_.jpg",
    brand: "Lava Agni 3",
    company: "Lava",
    price: 24999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 7300X",
    display: "6.78-inch AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50 MP + 8 MP + 8 MP",
    frontCamera: "16 MP",
    os: "Android 14",
    color: "Heather Glass",
  },
  {
    id: 9,
    slug: "redmi-13-5g",
    image: "https://m.media-amazon.com/images/I/81GhaMvvHTL._SX679_.jpg",
    brand: "Redmi 13 5G",
    company: "Redmi",
    price: 16999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 4 Gen 2 AE",
    display: "6.79-inch FHD+ LCD, 120Hz",
    battery: "5030 mAh",
    camera: "108 MP + 2 MP",
    frontCamera: "13 MP",
    os: "Android 14 (HyperOS)",
    color: "Black",
  },
  {
    id: 10,
    slug: "vivo-t5x-5g",
    image: "https://m.media-amazon.com/images/I/613RKG4NCgL._SX679_.jpg",
    brand: "vivo T5x 5G",
    company: "Vivo",
    price: 19980,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 7300",
    display: "6.72-inch FHD+ LCD, 120Hz",
    battery: "6500 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "8 MP",
    os: "Android 15 (Funtouch OS)",
    color: "Pronto Purple",
  },
];
export const formatPrice = (value) =>
  "₹" + Number(value).toLocaleString("en-IN");

export default products;
