const products = [
  {
    id: 1,
    slug: "samsung-galaxy-m17-5g",
    image: "https://m.media-amazon.com/images/I/41QOX6YsT5L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Samsung Galaxy M17 5G",
    company: "Samsung",
    price: 18999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Exynos 1380",
    display: "6.7-inch FHD+ Super AMOLED, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 8 MP + 2 MP",
    frontCamera: "13 MP",
    os: "Android 15 (One UI)",
    color: "Blue",
  },
  {
    id: 2,
    slug: "realme-c71-4g",
    image: "https://m.media-amazon.com/images/I/61yZ+3pjkYL._SX679_.jpg",
    brand: "realme C71 4G",
    company: "Realme",
    price: 15980,
    ram: "6 GB",
    storage: "128 GB",
    processor: "Unisoc T7250",
    display: "6.72-inch HD+ LCD, 120Hz",
    battery: "6300 mAh",
    camera: "50 MP AI Camera",
    frontCamera: "8 MP",
    os: "Android 15 (realme UI)",
    color: "Green",
  },
  {
    id: 3,
    slug: "motorola-edge-60-fusion",
    image: "https://m.media-amazon.com/images/I/61NsPikkMBL._SX679_.jpg",
    brand: "Motorola Edge 60 Fusion",
    company: "Motorola",
    price: 23999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 7400",
    display: "6.67-inch pOLED, 144Hz",
    battery: "5500 mAh",
    camera: "50 MP + 13 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "Forest Blue",
  },
  {
    id: 4,
    slug: "oppo-k14x-5g",
    image: "https://m.media-amazon.com/images/I/61wEl1TXntL._SX522_.jpg",
    brand: "OPPO K14x 5G",
    company: "OPPO",
    price: 15980,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 6300",
    display: "6.67-inch HD+ LCD, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "8 MP",
    os: "Android 15 (ColorOS)",
    color: "Midnight Violet",
  },
  {
    id: 5,
    slug: "acerpure-acerone-liquid-4g",
    image: "https://m.media-amazon.com/images/I/411RhleBYqL.jpg",
    brand: "Acerpure Acerone Liquid 4G",
    company: "Acer",
    price: 13599,
    ram: "6 GB",
    storage: "128 GB",
    processor: "MediaTek Helio G99",
    display: "6.78-inch FHD+ IPS LCD",
    battery: "5000 mAh",
    camera: "64 MP + 2 MP",
    frontCamera: "16 MP",
    os: "Android 14",
    color: "Black",
  },
  {
    id: 6,
    slug: "ikall-z10",
    image: "https://m.media-amazon.com/images/I/51UOnCphehL._SX679_.jpg",
    brand: "IKALL Z10",
    company: "IKALL",
    price: 11999,
    ram: "6 GB",
    storage: "128 GB",
    processor: "MediaTek Helio G85",
    display: "6.6-inch HD+ IPS LCD",
    battery: "5000 mAh",
    camera: "50 MP + AI Lens",
    frontCamera: "8 MP",
    os: "Android 14",
    color: "Black",
  },
  {
    id: 7,
    slug: "motorola-edge-60-pro",
    image: "https://m.media-amazon.com/images/I/71hbZwIVwQL._SY741_.jpg",
    brand: "Motorola Edge 60 Pro",
    company: "Motorola",
    price: 29999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 8350",
    display: "6.7-inch pOLED, 144Hz",
    battery: "6000 mAh",
    camera: "50 MP + 50 MP + 10 MP",
    frontCamera: "50 MP",
    os: "Android 15",
    color: "Pantone Shadow",
  },
  {
    id: 8,
    slug: "lava-agni-3",
    image: "https://m.media-amazon.com/images/I/71UdkYWXjCL._SX679_.jpg",
    brand: "Lava Agni 3",
    company: "Lava",
    price: 24999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 7300X",
    display: "6.78-inch AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50 MP + 8 MP + 8 MP",
    frontCamera: "16 MP",
    os: "Android 14",
    color: "Heather Glass",
  },
  {
    id: 9,
    slug: "redmi-13-5g",
    image: "https://m.media-amazon.com/images/I/81GhaMvvHTL._SX679_.jpg",
    brand: "Redmi 13 5G",
    company: "Redmi",
    price: 16999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 4 Gen 2 AE",
    display: "6.79-inch FHD+ LCD, 120Hz",
    battery: "5030 mAh",
    camera: "108 MP + 2 MP",
    frontCamera: "13 MP",
    os: "Android 14 (HyperOS)",
    color: "Black",
  },
  {
    id: 10,
    slug: "vivo-t5x-5g",
    image: "https://m.media-amazon.com/images/I/613RKG4NCgL._SX679_.jpg",
    brand: "vivo T5x 5G",
    company: "Vivo",
    price: 19980,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 7300",
    display: "6.72-inch FHD+ LCD, 120Hz",
    battery: "6500 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "8 MP",
    os: "Android 15 (Funtouch OS)",
    color: "Pronto Purple",
  },

  // 11
  {
    id: 11,
    slug: "samsung-galaxy-a36-5g",
    image: "https://m.media-amazon.com/images/I/31JN04QyHUL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Samsung Galaxy A36 5G",
    company: "Samsung",
    price: 32999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 6 Gen 3",
    display: "6.7-inch FHD+ Super AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50 MP + 8 MP + 5 MP",
    frontCamera: "12 MP",
    os: "Android 15 (One UI)",
    color: "Awesome Lavender",
  },

  // 12
  {
    id: 12,
    slug: "samsung-galaxy-s24-fe",
    image: "https://m.media-amazon.com/images/I/41hcjBeqDML._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Samsung Galaxy S24 FE",
    company: "Samsung",
    price: 54999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Exynos 2400e",
    display: "6.7-inch Dynamic AMOLED 2X, 120Hz",
    battery: "4700 mAh",
    camera: "50 MP + 12 MP + 8 MP",
    frontCamera: "10 MP",
    os: "Android 14 (One UI)",
    color: "Blue",
  },

  // 13
  {
    id: 13,
    slug: "oneplus-nord-ce5",
    image: "https://m.media-amazon.com/images/I/61IOa9IrlaL._SL1500_.jpg",
    brand: "OnePlus Nord CE5",
    company: "OnePlus",
    price: 24999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 8350",
    display: "6.77-inch AMOLED, 120Hz",
    battery: "7100 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "16 MP",
    os: "Android 15 (OxygenOS)",
    color: "Black",
  },

  // 14
  {
    id: 14,
    slug: "oneplus-13r",
    image: "https://m.media-amazon.com/images/I/41tOmpvOY3L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "OnePlus 13R",
    company: "OnePlus",
    price: 42999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8 Gen 3",
    display: "6.78-inch AMOLED, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 50 MP + 8 MP",
    frontCamera: "16 MP",
    os: "Android 15 (OxygenOS)",
    color: "Astral Trail",
  },

  // 15
  {
    id: 15,
    slug: "realme-gt-7",
    image: "https://m.media-amazon.com/images/I/41yqljm52PL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "realme GT 7",
    company: "Realme",
    price: 39999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 9400e",
    display: "6.78-inch AMOLED, 120Hz",
    battery: "7000 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "32 MP",
    os: "Android 15 (realme UI)",
    color: "IceSense Blue",
  },

  // 16
  {
    id: 16,
    slug: "poco-f7",
    image: "https://m.media-amazon.com/images/I/41oKU4ciWUL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "POCO F7",
    company: "POCO",
    price: 34999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8s Gen 4",
    display: "6.83-inch AMOLED, 120Hz",
    battery: "7550 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "20 MP",
    os: "Android 15 (HyperOS)",
    color: "Black",
  },

  // 17
  {
    id: 17,
    slug: "poco-x7-pro",
    image: "https://m.media-amazon.com/images/I/41Opbfpd-cL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "POCO X7 Pro",
    company: "POCO",
    price: 29999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 8400 Ultra",
    display: "6.67-inch AMOLED, 120Hz",
    battery: "6550 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "20 MP",
    os: "Android 15 (HyperOS)",
    color: "Yellow",
  },

  // 18
  {
    id: 18,
    slug: "redmi-note-14-pro-5g",
    image: "https://m.media-amazon.com/images/I/41JWY-kaRYL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Redmi Note 14 Pro 5G",
    company: "Redmi",
    price: 24999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "MediaTek Dimensity 7300 Ultra",
    display: "6.67-inch AMOLED, 120Hz",
    battery: "5500 mAh",
    camera: "200 MP + 8 MP + 2 MP",
    frontCamera: "20 MP",
    os: "Android 14 (HyperOS)",
    color: "Titan Black",
  },

  // 19
  {
    id: 19,
    slug: "vivo-v50",
    image: "https://m.media-amazon.com/images/I/41d3h132hRL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "vivo V50",
    company: "Vivo",
    price: 34999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 7 Gen 3",
    display: "6.77-inch AMOLED, 120Hz",
    battery: "6000 mAh",
    camera: "50 MP + 50 MP",
    frontCamera: "50 MP",
    os: "Android 15 (Funtouch OS)",
    color: "Rose Red",
  },

  // 20
  {
    id: 20,
    slug: "vivo-v50e",
    image: "https://m.media-amazon.com/images/I/41JrjsCQZPL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "vivo V50e",
    company: "Vivo",
    price: 28999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 7300",
    display: "6.77-inch AMOLED, 120Hz",
    battery: "5600 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "50 MP",
    os: "Android 15 (Funtouch OS)",
    color: "Sapphire Blue",
  },

  // 21
  {
    id: 21,
    slug: "oppo-reno-13-5g",
    image: "https://m.media-amazon.com/images/I/417rr4h4wBL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "OPPO Reno 13 5G",
    company: "OPPO",
    price: 37999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "MediaTek Dimensity 8350",
    display: "6.59-inch AMOLED, 120Hz",
    battery: "5600 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "50 MP",
    os: "Android 15 (ColorOS)",
    color: "Luminous Blue",
  },

  // 22
  {
    id: 22,
    slug: "oppo-f29-5g",
    image: "https://m.media-amazon.com/images/I/41mNAq3g5DL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "OPPO F29 5G",
    company: "OPPO",
    price: 26999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 6 Gen 1",
    display: "6.7-inch AMOLED, 120Hz",
    battery: "6500 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "16 MP",
    os: "Android 15 (ColorOS)",
    color: "Marble White",
  },

  // 23
  {
    id: 23,
    slug: "motorola-edge-50-fusion",
    image: "https://m.media-amazon.com/images/I/41LJegPvQsL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Motorola Edge 50 Fusion",
    company: "Motorola",
    price: 22999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 7s Gen 2",
    display: "6.7-inch pOLED, 144Hz",
    battery: "5000 mAh",
    camera: "50 MP + 13 MP",
    frontCamera: "32 MP",
    os: "Android 14",
    color: "Marshmallow Blue",
  },

  // 24
  {
    id: 24,
    slug: "motorola-g85-5g",
    image: "https://m.media-amazon.com/images/I/41FezyD8mjL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Motorola G85 5G",
    company: "Motorola",
    price: 18999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 6s Gen 3",
    display: "6.67-inch pOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "32 MP",
    os: "Android 14",
    color: "Olive Green",
  },

  // 25
  {
    id: 25,
    slug: "nothing-phone-3a",
    image: "https://m.media-amazon.com/images/I/417LpPEkRVL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Nothing Phone 3a",
    company: "Nothing",
    price: 24999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 7s Gen 3",
    display: "6.77-inch AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50 MP + 50 MP + 8 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "White",
  },

  // 26
  {
    id: 26,
    slug: "iqoo-neo-10",
    image: "https://m.media-amazon.com/images/I/41p5PSEky5L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "iQOO Neo 10",
    company: "iQOO",
    price: 31999,
    ram: "8 GB",
    storage: "256 GB",
    processor: "Snapdragon 8s Gen 4",
    display: "6.78-inch AMOLED, 144Hz",
    battery: "7000 mAh",
    camera: "50 MP + 8 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "Titanium Silver",
  },

  // 27
  {
    id: 27,
    slug: "iqoo-z10",
    image: "https://m.media-amazon.com/images/I/41Q9iRQgMjL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "iQOO Z10",
    company: "iQOO",
    price: 24999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Snapdragon 7s Gen 3",
    display: "6.77-inch AMOLED, 120Hz",
    battery: "7300 mAh",
    camera: "50 MP + 2 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "Glacier Silver",
  },

  // 28
  {
    id: 28,
    slug: "google-pixel-9a",
    image: "https://m.media-amazon.com/images/I/31cfYaN6msL._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Google Pixel 9a",
    company: "Google",
    price: 49999,
    ram: "8 GB",
    storage: "128 GB",
    processor: "Google Tensor G4",
    display: "6.3-inch Actua OLED, 120Hz",
    battery: "5100 mAh",
    camera: "48 MP + 13 MP",
    frontCamera: "13 MP",
    os: "Android 15",
    color: "Iris",
  },

  // 29
  {
    id: 29,
    slug: "asus-rog-phone-9",
    image: "https://m.media-amazon.com/images/I/41081KQik2L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "ASUS ROG Phone 9",
    company: "ASUS",
    price: 79999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8 Elite",
    display: "6.78-inch AMOLED, 185Hz",
    battery: "5800 mAh",
    camera: "50 MP + 13 MP + 5 MP",
    frontCamera: "32 MP",
    os: "Android 15",
    color: "Phantom Black",
  },

  // 30
  {
    id: 30,
    slug: "nothing-phone-3",
    image: "https://m.media-amazon.com/images/I/414m0VuRT+L._SY300_SX300_QL70_FMwebp_.jpg",
    brand: "Nothing Phone 3",
    company: "Nothing",
    price: 59999,
    ram: "12 GB",
    storage: "256 GB",
    processor: "Snapdragon 8s Gen 4",
    display: "6.67-inch AMOLED, 120Hz",
    battery: "5150 mAh",
    camera: "50 MP + 50 MP + 50 MP",
    frontCamera: "50 MP",
    os: "Android 15",
    color: "Black",
  },
];

export const formatPrice = (value) =>
  "₹" + Number(value).toLocaleString("en-IN");

export default products;